export const PRIVATE_DATA = {
  spaseID: process.env.NEXT_PUBLIC_SPACE_ID_JERSEY_BEHAVIORAL_CARE,
  accessId: process.env.NEXT_PUBLIC_ACCESS_ID_JERSEY_BEHAVIORAL_CARE,
  keyID: process.env.NEXT_PUBLIC_KEY_ID_JERSEY_BEHAVIORAL_CARE,
};
